#!/bin/bash -eux
source "$(dirname $0)/bin/conf"

[ "$USER" = "root" ] # USER MUST BE ROOT

mkdir -p "$logdir"
chown www-data:www-data "$logdir"

### INSTALL THIS SYSTEM ###
rsync -av --delete "$(dirname $0)/bin/" "$appdir/"
chown www-data:www-data "$appdir" -R

### RENAME FETCH CGI ###
cd "$appdir"
rnd=$(cat /dev/urandom | tr -dc 0-9a-zA-Z | head -c 32)
[ -e "${HOME}/rnd" ] && rnd=$(cat ${HOME}/rnd) # REMOVE ON RELEASE!!!
mv "fetch" "fetch_$rnd.cgi"

### PULL ARTICLE INFO ###
rm -rf "${contentsdir:?}"
cd "$wwwdir"
git clone "https://github.com/$contents_owner/$contents"
chown www-data:www-data "$contentsdir" -R

echo "call fetch_$rnd.cgi from GitHub"
